name: demo_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

 # get
  get: ^4.6.6
  get_storage: ^2.1.1

  retrofit: "4.1.0"
  # cached network image
  cached_network_image: ^3.3.1
  # intl
  intl: ^0.19.0

  # time ago
  timeago: ^3.7.0
  # tuple
  tuple: ^2.0.2
  # share
  share_plus: ^10.0.0
  # badges
  badges: ^3.1.2
  # permission handler
  permission_handler: ^10.2.0
  #for utill extensions
  nb_utils: 7.0.5
  # for loader
  flutter_overlay_loader: ^2.0.0
  # for loading svg files
  flutter_svg: ^2.0.10+1
  # for network requests
  dio: ^5.5.0+1
  # for oppening url in browser
  url_launcher: ^6.3.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_hooks: ^0.20.5
  get_it: ^7.7.0
  auto_route: ^7.8.4
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  dots_indicator: ^3.0.0
  easy_localization: ^3.0.7
  flutter_otp_text_field: ^1.1.1
  otp_text_field_v2: ^1.0.3
  pinput: ^5.0.0
  qr_flutter: ^4.1.0
  modal_bottom_sheet: ^3.0.0
  currency_text_input_formatter: ^2.2.3
  flutter_screenutil: ^5.9.3
  #qr_code_scanner:
  #git:
  #url: https://github.com/asmrtfm/qr_code_scanner
  #ref: patch-1
  #version: ^1.0.0
  dotted_border: ^2.1.0
  pdf: ^3.11.1

  path_provider: ^2.1.0
  #document_file_save_plus: ^2.0.0
  #IOS config needed
  image_picker: ^1.1.2
  #IOS config needed
  local_auth: ^2.3.0
  #IOS config needed
  nfc_manager: ^3.5.0
  nigerian_states_and_lga: ^1.0.0
  #IOS config needed
  paystack_for_flutter: ^1.0.2
  #pay_with_paystack: ^1.0.10
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  easy_refresh: ^3.4.0
  flutter_contacts: ^1.1.9+2
  progress_bar_steppers: ^0.0.2+2
  multi_select_flutter: ^4.1.3
  flutter_pin_code_fields: ^2.2.0

dependency_overrides:
  intl: ^0.17.0
  http: ^0.13.5

  auto_route: 7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^7.3.2
  retrofit_generator: "8.1.2"
  flutter_gen_runner: 5.6.0
  change_app_package_name: ^1.4.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

fonts:
     - family: jura
       fonts:
        - asset: fonts/jura-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  #line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    #flare_flutter: true
    #rive: true

  assets:
    enabled: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
